<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\sachiel.ico</ApplicationIcon>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <SatelliteResourceLanguages>es</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Icons\config.svg" />
    <None Remove="Resources\Icons\facturacion.svg" />
    <None Remove="Resources\Icons\home.svg" />
    <None Remove="Resources\Icons\logo-dark.svg" />
    <None Remove="Resources\Icons\logo-light.svg" />
    <None Remove="Resources\Icons\logo.svg" />
    <None Remove="Resources\Icons\productos.svg" />
    <None Remove="Resources\Icons\rendimientos.svg" />
    <None Remove="Resources\Icons\ventas.svg" />
    <None Remove="Resources\sachiel.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="Extended.Wpf.Toolkit" Version="5.1.2" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
    <PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
    <PackageReference Include="QuestPDF" Version="2024.3.10" />
    <PackageReference Include="SharpVectors.Wpf" Version="1.8.5" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.12" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Icons\config.svg" />
    <Resource Include="Resources\Icons\facturacion.svg" />
    <Resource Include="Resources\Icons\home.svg" />
    <Resource Include="Resources\Icons\logo-dark.svg" />
    <Resource Include="Resources\Icons\logo-light.svg" />
    <Resource Include="Resources\Icons\logo.svg" />
    <Resource Include="Resources\Icons\productos.svg" />
    <Resource Include="Resources\Icons\rendimientos.svg" />
    <Resource Include="Resources\Icons\ventas.svg" />
    <Resource Include="Resources\sachiel.ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Database\Backups\" />
    <Folder Include="Config\" />
  </ItemGroup>

</Project>
